export const GET_CARTS_REQUEST = "GET_CARTS_REQUEST"
export const GET_CARTS_SUCCESS = "GET_CARTS_SUCCESS"
export const GET_CARTS_FAILURE = "GET_CARTS_FAILURE"

export const ADD_CARTS_REQUEST = "ADD_CARTS_REQUEST"
export const ADD_CARTS_SUCCESS = "ADD_CARTS_SUCCESS"
export const ADD_CARTS_FAILURE = "ADD_CARTS_FAILURE"

export const UPDATE_CARTS_REQUEST = "UPDATE_CARTS_REQUEST"
export const UPDATE_CARTS_SUCCESS = "UPDATE_CARTS_SUCCESS"
export const UPDATE_CARTS_FAILURE = "UPDATE_CARTS_FAILURE"

export const DELETE_CARTS_REQUEST = "DELETE_CARTS_REQUEST"
export const DELETE_CARTS_SUCCESS = "DELETE_CARTS_SUCCESS"
export const DELETE_CARTS_FAILURE = "DELETE_CARTS_FAILURE"
